version: '3.8'

services:
  dev:
    image: thecodingmachine/php:7.4-v3-apache
    ports:
      - '5001:80'
    restart: unless-stopped
    environment:
      TEMPLATE_PHP_INI: "development"
      PHP_EXTENSION_XDEBUG: 1
      APACHE_DOCUMENT_ROOT: "public"
    volumes:
      - "./:/var/www/html"

  mysql-db:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=somerootpassword
      - MYSQL_USER=gaduser
      - MYSQL_PASSWORD=gadpass
      - MYSQL_DATABASE=gad
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - '5002:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql-db
    ports:
      - '5003:80'
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: somerootpassword

volumes:
  db-data:
